'use client';

import { useState } from 'react';

const NFT_TEMPLATE = (name: string, symbol: string, maxSupply: number) => `
;; ${name} NFT Contract
;; Auto-generated by STX Builder

(impl-trait 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait.nft-trait)

(define-non-fungible-token ${symbol} uint)

(define-constant DEPLOYER tx-sender)
(define-constant ERR-NOT-AUTHORIZED (err u100))
(define-constant ERR-SOLD-OUT (err u101))

(define-data-var last-id uint u0)
(define-constant MAX-SUPPLY u${maxSupply})

;; Deployment Fee: 0.05 STX sent to platform
(try! (stx-transfer? u50000 tx-sender 'SP2F500B8DTRK1EANJQ054BRAB8DDKN6QCMXGNFBT))

(define-read-only (get-last-token-id)
    (ok (var-get last-id))
)

(define-read-only (get-token-uri (token-id uint))
    (ok none)
)

(define-read-only (get-owner (token-id uint))
    (ok (nft-get-owner? ${symbol} token-id))
)

(define-public (transfer (token-id uint) (sender principal) (recipient principal))
    (begin
        (asserts! (is-eq tx-sender sender) ERR-NOT-AUTHORIZED)
        (nft-transfer? ${symbol} token-id sender recipient)
    )
)

(define-public (mint (recipient principal))
    (let
        (
            (next-id (+ (var-get last-id) u1))
        )
        (asserts! (< (var-get last-id) MAX-SUPPLY) ERR-SOLD-OUT)
        (try! (nft-mint? ${symbol} next-id recipient))
        (var-set last-id next-id)
        (ok next-id)
    )
)
`;

const STANDARD_TEMPLATE = `
;; Simple Storage Contract
;; Deployment Fee: 0.05 STX sent to platform
(try! (stx-transfer? u50000 tx-sender 'SP2F500B8DTRK1EANJQ054BRAB8DDKN6QCMXGNFBT))

(define-data-var message (string-utf8 500) u"Hello Stacks")

(define-public (write-message (new-message (string-utf8 500)))
    (begin
        (print new-message)
        (var-set message new-message)
        (ok "Message updated")
    )
)

(define-read-only (read-message)
    (ok (var-get message))
)
`;

export function ContractDeployer() {
    const [deployType, setDeployType] = useState<'standard' | 'nft'>('standard');
    const [contractName, setContractName] = useState('');
    const [code, setCode] = useState(STANDARD_TEMPLATE);

    // NFT State
    const [nftName, setNftName] = useState('MyNFT');
    const [nftSymbol, setNftSymbol] = useState('MNFT');
    const [maxSupply, setMaxSupply] = useState(1000);

    const [status, setStatus] = useState('');

    const handleDeploy = async () => {
        if (!contractName) {
            setStatus('enter contract name');
            return;
        }

        setStatus('preparing deployment...');

        try {
            const { openContractDeploy } = await import('@stacks/connect');
            const { AnchorMode } = await import('@stacks/transactions');
            const { StacksMainnet } = await import('@stacks/network');

            let codeBody = code;
            if (deployType === 'nft') {
                codeBody = NFT_TEMPLATE(nftName, nftSymbol, maxSupply);
            }

            await openContractDeploy({
                contractName,
                codeBody,
                network: new StacksMainnet(),
                anchorMode: AnchorMode.Any,
                onFinish: (data) => {
                    setStatus(`✅ Deployed! TX: ${data.txId}`);
                },
                onCancel: () => {
                    setStatus('❌ Cancelled');
                },
            });
        } catch (e) {
            setStatus('❌ Error: ' + (e as Error).message);
        }
    };

    return (
        <div className="glass-card" style={{ marginTop: '2rem' }}>
            <h2>🛠️ Contract Deployer</h2>

            <div style={{ display: 'flex', gap: '1rem', margin: '1rem 0' }}>
                <button
                    className={`btn ${deployType === 'standard' ? 'btn-primary' : ''}`}
                    onClick={() => setDeployType('standard')}
                    style={{ opacity: deployType === 'standard' ? 1 : 0.6 }}
                >
                    📜 Standard
                </button>
                <button
                    className={`btn ${deployType === 'nft' ? 'btn-primary' : ''}`}
                    onClick={() => setDeployType('nft')}
                    style={{ opacity: deployType === 'nft' ? 1 : 0.6 }}
                >
                    🖼️ NFT Collection
                </button>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                <input
                    type="text"
                    placeholder="Contract Name (e.g. my-cool-contract)"
                    value={contractName}
                    onChange={(e) => setContractName(e.target.value.replace(/\s+/g, '-').toLowerCase())}
                    style={{
                        padding: '0.8rem',
                        borderRadius: '8px',
                        background: 'rgba(255,255,255,0.1)',
                        border: '1px solid rgba(255,255,255,0.2)',
                        color: 'white'
                    }}
                />

                {deployType === 'nft' ? (
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                        <input
                            placeholder="Result Name (e.g. Bored Apes)"
                            value={nftName}
                            onChange={(e) => setNftName(e.target.value)}
                            className="glass-input"
                        />
                        <input
                            placeholder="Symbol (e.g. BAYC)"
                            value={nftSymbol}
                            onChange={(e) => setNftSymbol(e.target.value)}
                            className="glass-input"
                        />
                        <input
                            type="number"
                            placeholder="Max Supply"
                            value={maxSupply}
                            onChange={(e) => setMaxSupply(parseInt(e.target.value))}
                            className="glass-input"
                        />
                    </div>
                ) : (
                    <textarea
                        value={code}
                        onChange={(e) => setCode(e.target.value)}
                        rows={10}
                        style={{
                            fontFamily: 'monospace',
                            padding: '1rem',
                            background: 'rgba(0,0,0,0.3)',
                            color: '#0f0',
                            borderRadius: '8px',
                            border: '1px solid rgba(255,255,255,0.1)'
                        }}
                    />
                )}

                <button className="btn btn-primary" onClick={handleDeploy}>
                    🚀 Deploy {deployType === 'nft' ? 'NFT' : 'Contract'}
                </button>

                {status && <p style={{ marginTop: '0.5rem' }}>{status}</p>}
            </div>
        </div>
    );
}
