'use client';

import { useState } from 'react';

const NFT_TEMPLATE = (name: string, symbol: string, maxSupply: number) => `
;; ${name} NFT Contract
;; Auto-generated by STX Builder

(impl-trait 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait.nft-trait)

(define-non-fungible-token ${symbol} uint)

(define-constant DEPLOYER tx-sender)
(define-constant ERR-NOT-AUTHORIZED (err u100))
(define-constant ERR-SOLD-OUT (err u101))

(define-data-var last-id uint u0)
(define-constant MAX-SUPPLY u${maxSupply})

;; Deployment Fee: 0.05 STX sent to platform
(try! (stx-transfer? u50000 tx-sender 'SP2F500B8DTRK1EANJQ054BRAB8DDKN6QCMXGNFBT))

(define-read-only (get-last-token-id)
    (ok (var-get last-id))
)

(define-read-only (get-token-uri (token-id uint))
    (ok none)
)

(define-read-only (get-owner (token-id uint))
    (ok (nft-get-owner? ${symbol} token-id))
)

(define-public (transfer (token-id uint) (sender principal) (recipient principal))
    (begin
        (asserts! (is-eq tx-sender sender) ERR-NOT-AUTHORIZED)
        (nft-transfer? ${symbol} token-id sender recipient)
    )
)

(define-public (mint (recipient principal))
    (let
        (
            (next-id (+ (var-get last-id) u1))
        )
        (asserts! (< (var-get last-id) MAX-SUPPLY) ERR-SOLD-OUT)
        (try! (nft-mint? ${symbol} next-id recipient))
        (var-set last-id next-id)
        (ok next-id)
    )
)
`;

const STANDARD_TEMPLATE = `
;; Simple Storage Contract
;; Deployment Fee: 0.05 STX sent to platform
(try! (stx-transfer? u50000 tx-sender 'SP2F500B8DTRK1EANJQ054BRAB8DDKN6QCMXGNFBT))

(define-data-var message (string-utf8 500) u"Hello Stacks")

(define-public (write-message (new-message (string-utf8 500)))
    (begin
        (print new-message)
        (var-set message new-message)
        (ok "Message updated")
    )
)

(define-read-only (read-message)
    (ok (var-get message))
)
`;

import { CONTRACT_TEMPLATES } from '../lib/contract-templates';

export function ContractDeployer() {
    const [deployType, setDeployType] = useState<'standard' | 'nft'>('standard');
    const [contractName, setContractName] = useState('');
    const [code, setCode] = useState(STANDARD_TEMPLATE);
    const [showTemplates, setShowTemplates] = useState(false);

    // NFT State
    const [nftName, setNftName] = useState('MyNFT');
    const [nftSymbol, setNftSymbol] = useState('MNFT');
    const [maxSupply, setMaxSupply] = useState(1000);

    const [status, setStatus] = useState('');


    // Helper to copy code to clipboard
    const copyToClipboard = () => {
        const codeToCopy = deployType === 'nft' ? NFT_TEMPLATE(nftName, nftSymbol, maxSupply) : code;
        navigator.clipboard.writeText(codeToCopy);
        setStatus('📋 Code copied to clipboard!');
        setTimeout(() => setStatus(''), 2000);
    };

    // Helper to download code as .clar file
    const downloadContract = () => {
        if (!contractName) {
            setStatus('⚠️ Please enter a contract name first');
            return;
        }
        const codeToDownload = deployType === 'nft' ? NFT_TEMPLATE(nftName, nftSymbol, maxSupply) : code;
        const blob = new Blob([codeToDownload], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${contractName}.clar`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        setStatus(`⬇️ Downloaded ${contractName}.clar`);
    };

    /**
     * Handles the contract deployment process.
     * Generates code based on template and triggers Stacks Connect popup.
     */
    const handleDeploy = async () => {
        if (!contractName) {
            setStatus('⚠️ Please enter a contract name');
            return;
        }

        setStatus('⏳ Preparing deployment...');

        try {
            const { openContractDeploy } = await import('@stacks/connect');
            const { AnchorMode } = await import('@stacks/transactions');

            let codeBody = code;
            if (deployType === 'nft') {
                codeBody = NFT_TEMPLATE(nftName, nftSymbol, maxSupply);
            }

            await openContractDeploy({
                contractName,
                codeBody,
                network: 'mainnet', // Use string instead of network object
                anchorMode: AnchorMode.Any,
                onFinish: (data) => {
                    setStatus(`✅ Deployed! TX: ${data.txId}`);
                },
                onCancel: () => {
                    setStatus('❌ Transaction cancelled');
                },
            });
        } catch (e) {
            console.error(e);
            setStatus('❌ Error: ' + (e as Error).message);
        }
    };

    return (
        <div className="glass-card" style={{ marginTop: '2rem', border: '1px solid rgba(16, 185, 129, 0.2)', position: 'relative', overflow: 'hidden' }}>
            <div style={{ position: 'absolute', top: 0, right: 0, width: '150px', height: '150px', background: 'radial-gradient(circle, rgba(16, 185, 129, 0.1) 0%, transparent 70%)', pointerEvents: 'none' }}></div>
            <h2>🛠️ Contract Deployer</h2>

            <div style={{ display: 'flex', gap: '1rem', margin: '1.5rem 0', padding: '4px', background: 'rgba(0,0,0,0.2)', borderRadius: '14px', width: 'fit-content' }}>
                <button
                    className={`btn`}
                    onClick={() => setDeployType('standard')}
                    style={{
                        background: deployType === 'standard' ? 'rgba(99, 102, 241, 0.2)' : 'transparent',
                        color: deployType === 'standard' ? '#818cf8' : '#94a3b8',
                        border: 'none',
                        boxShadow: 'none',
                        transition: 'all 0.3s ease'
                    }}
                >
                    📜 Standard
                </button>
                <button
                    className={`btn`}
                    onClick={() => setDeployType('nft')}
                    style={{
                        background: deployType === 'nft' ? 'rgba(236, 72, 153, 0.2)' : 'transparent',
                        color: deployType === 'nft' ? '#f472b6' : '#94a3b8',
                        border: 'none',
                        boxShadow: 'none',
                        transition: 'all 0.3s ease'
                    }}
                >
                    🖼️ NFT Collection
                </button>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
                <div>
                    <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: '#94a3b8', fontWeight: '500' }}>
                        Contract Name
                    </label>
                    <input
                        type="text"
                        placeholder="e.g. my-cool-contract"
                        value={contractName}
                        onChange={(e) => setContractName(e.target.value.replace(/\s+/g, '-').toLowerCase())}
                        style={{
                            width: '100%',
                            padding: '1rem',
                            borderRadius: '12px',
                            background: 'rgba(0,0,0,0.2)',
                            border: '1px solid rgba(255,255,255,0.1)',
                            color: 'white',
                            fontSize: '1rem',
                            fontFamily: 'monospace'
                        }}
                    />
                </div>

                {deployType === 'nft' ? (
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem' }}>
                        <div>
                            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: '#94a3b8' }}>Name</label>
                            <input
                                placeholder="e.g. Bored Apes"
                                value={nftName}
                                onChange={(e) => setNftName(e.target.value)}
                                className="glass-input"
                                style={{ width: '100%', padding: '1rem', borderRadius: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)', color: 'white' }}
                            />
                        </div>
                        <div>
                            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: '#94a3b8' }}>Symbol</label>
                            <input
                                placeholder="e.g. BAYC"
                                value={nftSymbol}
                                onChange={(e) => setNftSymbol(e.target.value)}
                                className="glass-input"
                                style={{ width: '100%', padding: '1rem', borderRadius: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)', color: 'white' }}
                            />
                        </div>
                        <div>
                            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: '#94a3b8' }}>Max Supply</label>
                            <input
                                type="number"
                                placeholder="1000"
                                value={maxSupply}
                                onChange={(e) => setMaxSupply(parseInt(e.target.value))}
                                className="glass-input"
                                style={{ width: '100%', padding: '1rem', borderRadius: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)', color: 'white' }}
                            />
                        </div>
                    </div>
                ) : (
                    <textarea
                        value={code}
                        onChange={(e) => setCode(e.target.value)}
                        rows={12}
                        placeholder="Write your Clarity code here..."
                        style={{
                            fontFamily: 'monospace',
                            padding: '1.25rem',
                            background: '#0f172a',
                            color: '#a5b4fc',
                            borderRadius: '12px',
                            border: '1px solid rgba(99, 102, 241, 0.2)',
                            width: '100%',
                            lineHeight: '1.5',
                            fontSize: '0.9rem'
                        }}
                    />
                )}

                <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap' }}>
                    <button className="btn" onClick={copyToClipboard} style={{ background: 'rgba(255,255,255,0.05)', fontSize: '0.9rem' }}>
                        📋 Copy Code
                    </button>
                    <button className="btn" onClick={downloadContract} style={{ background: 'rgba(255,255,255,0.05)', fontSize: '0.9rem' }}>
                        ⬇️ Download .clar
                    </button>
                    <button
                        className="btn"
                        onClick={() => setShowTemplates(!showTemplates)}
                        style={{ background: showTemplates ? 'rgba(99, 102, 241, 0.4)' : 'rgba(99, 102, 241, 0.2)', fontSize: '0.9rem', color: '#a5b4fc' }}>
                        📚 Select Template ({CONTRACT_TEMPLATES.length})
                    </button>
                </div>

                {showTemplates && (
                    <div style={{
                        background: 'rgba(0,0,0,0.3)',
                        borderRadius: '12px',
                        padding: '1rem',
                        maxHeight: '300px',
                        overflowY: 'auto',
                        border: '1px solid rgba(255,255,255,0.1)'
                    }}>
                        <h4 style={{ margin: '0 0 1rem 0', color: '#fff' }}>Available Templates</h4>
                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: '0.75rem' }}>
                            {CONTRACT_TEMPLATES.map(t => (
                                <div
                                    key={t.id}
                                    onClick={() => {
                                        setCode(t.code);
                                        setContractName(t.id);
                                        setDeployType('standard');
                                        setShowTemplates(false);
                                        setStatus(`Loaded template: ${t.name}`);
                                    }}
                                    style={{
                                        background: 'rgba(255,255,255,0.05)',
                                        padding: '0.75rem',
                                        borderRadius: '8px',
                                        cursor: 'pointer',
                                        border: '1px solid rgba(255,255,255,0.05)',
                                        transition: 'all 0.2s',
                                        fontSize: '0.9rem'
                                    }}
                                    onMouseOver={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.1)'}
                                    onMouseOut={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.05)'}
                                >
                                    <div style={{ fontWeight: 'bold', color: '#e2e8f0', marginBottom: '4px' }}>{t.name}</div>
                                    <div style={{ fontSize: '0.75rem', color: '#94a3b8', lineHeight: '1.2' }}>{t.description.slice(0, 40)}...</div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                <div style={{ borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '1.5rem', marginTop: '0.5rem' }}>
                    <button className="btn btn-primary" onClick={handleDeploy} style={{
                        width: '100%',
                        padding: '1rem',
                        fontSize: '1.1rem',
                        background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
                        boxShadow: '0 4px 14px rgba(16, 185, 129, 0.4)'
                    }}>
                        🚀 Deploy {deployType === 'nft' ? 'NFT Collection' : 'Smart Contract'}
                    </button>
                    <p style={{ textAlign: 'center', fontSize: '0.8rem', color: '#94a3b8', marginTop: '0.75rem' }}>
                        Deployment includes a small platform fee (0.05 STX)
                    </p>
                </div>

                {status && (
                    <div style={{
                        padding: '1rem',
                        borderRadius: '12px',
                        background: status.includes('Error') || status.includes('Cancelled') ? 'rgba(239, 68, 68, 0.1)' : 'rgba(16, 185, 129, 0.1)',
                        border: '1px solid ' + (status.includes('Error') ? 'rgba(239, 68, 68, 0.2)' : 'rgba(16, 185, 129, 0.2)'),
                        color: status.includes('Error') || status.includes('Cancelled') ? '#fca5a5' : '#6ee7b7',
                        textAlign: 'center',
                        fontWeight: '500',
                        animation: 'fadeIn 0.3s ease-out'
                    }}>
                        {status}
                    </div>
                )}
            </div>
        </div>
    );
}
